source :rubygems

gem "adsf"
gem "babosa"
gem "builder"
gem "closure-compiler"
gem "compass", "~> 0.13.alpha.0"
gem "configatron", "= 2.9.1"
gem "haml"
gem "hash-deep-merge"
gem "kramdown"
gem "mime-types"
gem "nanoc"
gem "nanoc-cachebuster"
gem "nokogiri"
gem "piston"
gem "rainpress"
gem "rake"
gem "rspec"
gem "sanitize"
gem "sass", "~> 3.2.0.alpha.101"
gem "listen"
